name: Deploy Corexus Frontend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Trigger only on changes within the frontend directory

env:
  HEROKU_APP_NAME: corexus-frontend-ali
  HEROKU_EMAIL: hello@alihamxa.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy frontend to Heroku
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku `git subtree split --prefix frontend HEAD`:main --force
