name: Deploy Corexus Backend to Heroku

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Trigger only on changes within the backend directory

env:
  HEROKU_APP_NAME: corexus-backend-ali
  HEROKU_EMAIL: hello@alihamxa.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend to Heroku
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/$HEROKU_APP_NAME.git
          git subtree push --prefix backend heroku main
